# Generated by Django 3.2.3 on 2021-05-14 03:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountWells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wells_status', models.CharField(max_length=255, verbose_name='Status')),
                ('wells_count', models.IntegerField(verbose_name='Quantity')),
            ],
            options={
                'verbose_name': 'Count of wells',
                'verbose_name_plural': 'Count of wells',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_employee', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Employee number')),
                ('email', models.EmailField(max_length=40, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('middle_name', models.CharField(blank=True, max_length=30, verbose_name='middle name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='phone number')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateField(verbose_name='Date of the incident')),
                ('incident_count', models.IntegerField(verbose_name='Quantity')),
                ('incident_details', models.TextField(verbose_name='Detailed description')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
            },
        ),
        migrations.CreateModel(
            name='OilField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('asurg', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='ASURG Equipment')),
                ('gas_disposal', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Gas utilization')),
            ],
            options={
                'verbose_name': 'Oil field',
                'verbose_name_plural': 'Oil fields',
            },
        ),
        migrations.CreateModel(
            name='Urgg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgg_date', models.DateField()),
                ('urgg_count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'URGG indicator',
                'verbose_name_plural': 'URGG indicators',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateField(verbose_name='Task date')),
                ('task_details', models.CharField(max_length=255, verbose_name='Task details')),
                ('id_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='info.employee', to_field='id_employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='Mining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mining_date', models.DateField(verbose_name='Date')),
                ('mining_value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Production quantity')),
                ('name_oilfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mining', to='info.oilfield', verbose_name='Oil field')),
            ],
            options={
                'verbose_name': 'Mining',
                'verbose_name_plural': 'Minings',
            },
        ),
    ]
