# Generated by Django 3.2.3 on 2021-05-31 13:29

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_employee', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Номер сотрудника')),
                ('email', models.EmailField(max_length=40, unique=True, verbose_name='Электронная почта')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateField(verbose_name='Дата инцидента')),
                ('incident_count', models.IntegerField(verbose_name='Количество')),
                ('incident_details', models.TextField(verbose_name='Подробное описание')),
            ],
            options={
                'verbose_name': 'Инцидент',
                'verbose_name_plural': 'Инциденты',
            },
        ),
        migrations.CreateModel(
            name='OilField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Месторождение',
                'verbose_name_plural': 'Месторождения',
            },
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_type', models.CharField(choices=[('0', 'Добывающая'), ('1', 'Нагнетательная'), ('2', 'Специальная'), ('3', 'Вспомогательная')], default='0', max_length=15, verbose_name='Тип скважины')),
                ('ident_number', models.CharField(max_length=100, verbose_name='Идентификационный номер')),
                ('asurg', models.BooleanField(default=False, verbose_name='Оснащение АСУРГ')),
                ('oilfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oilfield', to='info.oilfield', verbose_name='Месторождение')),
            ],
            options={
                'verbose_name': 'Скважина',
                'verbose_name_plural': 'Скважины',
            },
        ),
        migrations.CreateModel(
            name='Urgg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgg_date', models.DateField()),
                ('urgg_count', models.IntegerField()),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urgg', to='info.well', verbose_name='Скважина')),
            ],
            options={
                'verbose_name': 'Показатель УРГГ',
                'verbose_name_plural': 'Показатели УРГГ',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateField(verbose_name='Дата задачи')),
                ('task_details', models.CharField(max_length=255, verbose_name='Подробное описание')),
                ('id_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='info.employee', to_field='id_employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='Mining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mining_date', models.DateField(verbose_name='Дата')),
                ('mining_count', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Количество добычи')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mining', to='info.well', verbose_name='Скважина')),
            ],
            options={
                'verbose_name': 'Добыча',
                'verbose_name_plural': 'Добыча',
            },
        ),
        migrations.CreateModel(
            name='GasDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_disposal_date', models.DateField(verbose_name='Дата')),
                ('gas_disposal_count', models.IntegerField(verbose_name='Количество')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_deposal', to='info.well', verbose_name='Скважина')),
            ],
            options={
                'verbose_name': 'Утилизация газа',
                'verbose_name_plural': 'Утилизация газа',
            },
        ),
    ]
