# Generated by Django 3.2.3 on 2021-05-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasdisposal',
            name='gas_disposal_count',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='mining',
            name='mining_count',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='urgg',
            name='urgg_count',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='urgg',
            name='urgg_date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
