# Generated by Django 3.2.3 on 2021-05-16 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mining',
            options={'verbose_name': 'Minings', 'verbose_name_plural': 'Minings'},
        ),
    ]
