# Generated by Django 3.2.3 on 2021-06-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20210531_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='well_status',
            field=models.CharField(choices=[('0', 'Бурение'), ('1', 'Освоение'), ('2', 'Бездействие'), ('3', 'Простой')], default='2', max_length=15, verbose_name='Статус скважины'),
        ),
    ]
