# Generated by Django 3.2.3 on 2021-05-17 07:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_mining_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countwells',
            options={'verbose_name': 'Количество скважин', 'verbose_name_plural': 'Количество скважин'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'verbose_name': 'Инцидент', 'verbose_name_plural': 'Инциденты'},
        ),
        migrations.AlterModelOptions(
            name='mining',
            options={'verbose_name': 'Добыча', 'verbose_name_plural': 'Добыча'},
        ),
        migrations.AlterModelOptions(
            name='oilfield',
            options={'verbose_name': 'Месторождение', 'verbose_name_plural': 'Месторождения'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='urgg',
            options={'verbose_name': 'Показатель УРГГ', 'verbose_name_plural': 'Показатели УРГГ'},
        ),
        migrations.AlterField(
            model_name='countwells',
            name='wells_count',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='countwells',
            name='wells_status',
            field=models.CharField(max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=40, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_employee',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Номер сотрудника'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_count',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_date',
            field=models.DateField(verbose_name='Дата инцидента'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_details',
            field=models.TextField(verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='mining',
            name='mining_date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='mining',
            name='mining_value',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Количество добычи'),
        ),
        migrations.AlterField(
            model_name='mining',
            name='name_oilfield',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mining', to='info.oilfield', verbose_name='Месторождение'),
        ),
        migrations.AlterField(
            model_name='oilfield',
            name='asurg',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Оснащение АСУРГами'),
        ),
        migrations.AlterField(
            model_name='oilfield',
            name='gas_disposal',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Утилизация газа'),
        ),
        migrations.AlterField(
            model_name='oilfield',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='info.employee', to_field='id_employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.DateField(verbose_name='Дата задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_details',
            field=models.CharField(max_length=255, verbose_name='Подробное описание'),
        ),
    ]
