# Generated by Django 3.1.7 on 2021-04-02 12:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountWells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_wells', models.CharField(max_length=255, verbose_name='Статус')),
                ('count_wells', models.IntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Количество скважин',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_incident', models.DateField(verbose_name='Дата инцидента')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('details', models.TextField(verbose_name='Подробное описание')),
            ],
            options={
                'verbose_name': 'Инцидент',
                'verbose_name_plural': 'Инциденты',
            },
        ),
        migrations.CreateModel(
            name='OilField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('asurg', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Оснащение АСУРГами')),
                ('gas_disposal', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Утилизация газа')),
            ],
            options={
                'verbose_name': 'Месторождение',
                'verbose_name_plural': 'Месторождения',
            },
        ),
        migrations.CreateModel(
            name='Urgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_urgg', models.DateField()),
                ('count_urgg', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Показатель УРГГ',
                'verbose_name_plural': 'Показатели УРГГ',
            },
        ),
        migrations.CreateModel(
            name='Mining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mining', models.DateField(verbose_name='Дата')),
                ('mining_value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Количество добычи')),
                ('name_oilfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mining', to='demo.oilfield', verbose_name='Месторождение')),
            ],
            options={
                'verbose_name': 'Добыча',
            },
        ),
    ]
