# Generated by Django 3.1.7 on 2021-04-09 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_employee', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Номер сотрудника')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО сотрудника')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.AlterModelOptions(
            name='mining',
            options={'verbose_name': 'Добыча', 'verbose_name_plural': 'Добыча'},
        ),
        migrations.RenameField(
            model_name='countwells',
            old_name='count_wells',
            new_name='wells_count',
        ),
        migrations.RenameField(
            model_name='countwells',
            old_name='status_wells',
            new_name='wells_status',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='count',
            new_name='incident_count',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='date_incident',
            new_name='incident_date',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='details',
            new_name='incident_details',
        ),
        migrations.RenameField(
            model_name='mining',
            old_name='date_mining',
            new_name='mining_date',
        ),
        migrations.RenameField(
            model_name='urgg',
            old_name='count_urgg',
            new_name='urgg_count',
        ),
        migrations.RenameField(
            model_name='urgg',
            old_name='date_urgg',
            new_name='urgg_date',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateField(verbose_name='Дата задачи')),
                ('task_details', models.CharField(max_length=255, verbose_name='Описание задачи')),
                ('id_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='demo.employee', to_field='id_employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
