# Generated by Django 3.1.7 on 2021-04-14 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20210409_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countwells',
            options={'verbose_name': 'Количество скважин', 'verbose_name_plural': 'Количество скважин'},
        ),
    ]
