  on:
    push:
      branches: [ dev ]
  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: print
          run:
            echo ${{ secrets.GIT_REMOTE_URL }}
        - name: Dokku
          uses: dokku/github-action@v1.0.1
          with:
            git_remote_url: ssh://dokku@82.148.17.80:3210/ga/
            ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
            ssh_host_key: ${{ secrets.SSH_HOST_KEY }}
